[package]
name = "digisurf"
version = "0.1.0"
edition = "2021"
include = ["resources/**/*"]

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
crossterm = "0.28.1"
lazy_static = "1.5.0"
nom = "8.0.0"
ratatui = "0.29.0"

[dev-dependencies]
insta = "1.42.1"
tempfile = "3.17.1"
